---
kind: pipeline
name: linting

platform:
  os: linux
  arch: amd64

steps:
- name: later
  image: xoxys/ansible-later:latest
  commands:
  - ansible-later

trigger:
  ref:
  - refs/heads/master
  - refs/tags/**
  - refs/pull/**

---
kind: pipeline
name: testing-ubuntu1804

platform:
  os: linux
  arch: amd64

concurrency:
  limit: 1

workspace:
  base: /drone/src
  path: apache

steps:
- name: molecule
  image: xoxys/molecule:hcloud-linux-amd64
  commands:
  - /bin/bash /docker-entrypoint.sh
  - molecule test -s ubuntu1804
  environment:
    HCLOUD_TOKEN:
      from_secret: hcloud_token
    PY_COLORS: 1
    USER: root

trigger:
  ref:
  - refs/heads/master
  - refs/tags/**
  - refs/pull/**

depends_on:
- linting

---
kind: pipeline
name: testing-centos7

platform:
  os: linux
  arch: amd64

concurrency:
  limit: 1

workspace:
  base: /drone/src
  path: apache

steps:
- name: molecule
  image: xoxys/molecule:hcloud-linux-amd64
  commands:
  - /bin/bash /docker-entrypoint.sh
  - molecule test -s centos7
  environment:
    HCLOUD_TOKEN:
      from_secret: hcloud_token
    PY_COLORS: 1
    USER: root

trigger:
  ref:
  - refs/heads/master
  - refs/tags/**
  - refs/pull/**

depends_on:
- linting

---
kind: pipeline
name: documentation

platform:
  os: linux
  arch: amd64

steps:
- name: generate
  image: xoxys/ansible-doctor:latest
  environment:
    ANSIBLE_DOCTOR_CUSTOM_HEADER: HEADER.md
    ANSIBLE_DOCTOR_EXCLUDE_FILES: molecule/
    ANSIBLE_DOCTOR_FORCE_OVERWRITE: true
    ANSIBLE_DOCTOR_LOG_LEVEL: INFO

- name: commit
  image: plugins/git-action:latest
  settings:
    actions:
    - commit
    - push
    author_email:
      from_secret: github_author_email
    author_name: ownClouders
    branch: master
    message: "[SKIP CI] update readme"
    netrc_machine: " github.com"
    netrc_password:
      from_secret: github_token
    netrc_username:
      from_secret: github_username
    remote: https://github.com/owncloud-ansible/apache
  when:
    ref:
    - refs/heads/master

trigger:
  ref:
  - refs/heads/master
  - refs/tags/**
  - refs/pull/**

depends_on:
- testing-ubuntu1804
- testing-centos7

---
kind: pipeline
name: notification

platform:
  os: linux
  arch: amd64

steps:
- name: notify
  image: plugins/slack:1
  settings:
    channel:
      from_secret: slack_channel
    webhook:
      from_secret: slack_webhook_private

trigger:
  ref:
  - refs/heads/master
  - refs/tags/**
  status:
  - success
  - failure

depends_on:
- linting
- testing-ubuntu1804
- testing-centos7
- documentation

---
kind: signature
hmac: 36bce26dd66a6da8b203c5c6622a876d1732e44433545925b289c8e9df636abc

...
