---
- name: Enable Apache mods
  apache2_module:
    name: "{{ item }}"
    state: present
  loop: "{{ apache_mods_enabled }}"
  notify: __apache_restart

- name: Disable Apache mods
  apache2_module:
    name: "{{ item }}"
    state: absent
  loop: "{{ apache_mods_disabled }}"
  notify: __apache_restart

- name: Remove default vhost in sites-enabled
  file:
    path: "{{ apache_conf_path }}/vhosts.d/{{ apache_default_vhost_name }}"
    state: absent
  notify: __apache_restart

- name: Setup sysconfig
  replace:
    path: "{{ __apache_sysconfig_path }}"
    regexp: "{{ item.regexp }}"
    replace: "{{ item.replace }}"
  loop: "{{ __apache_sysconfig_items }}"
  notify: __apache_restart

- name: Add apache vhosts configuration
  template:
    src: owncloud.conf.j2
    dest: "{{ apache_conf_path }}/vhosts.d/{{ apache_vhost_name }}"
    owner: root
    group: root
    mode: 0644
  notify: __apache_restart
